# Exercice 01 

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## 1-

In [3]:
Z = np.array([
    [14,13,1.50,45],
    [16,13,1.60,50],
    [15,13,1.65,50],
    [9,15,1.75,60],
    [10,14,1.70,60],
    [7,14,1.70,60],
    [8,14,1.60,70],
    [13,13,1.60,65],
    [17,15,1.55,60],
    [11,14,1.70,65]
])

# Normalisation des données
Z = (Z - Z.mean(axis=0)) / Z.std(axis=0)

print("-----------------------------------------------------------------------------")
print(Z)
print("-----------------------------------------------------------------------------")

# Matrice de covariance

X = np.corrcoef(Z.T)

print(X)
print("-----------------------------------------------------------------------------")

# Valeurs propres et vecteurs propres de la matrice de covariance

eigval, eigvec = np.linalg.eig(X)

print(eigval)
print("-----------------------------------------------------------------------------")

# Tri des valeurs propres (car on veut les plus grandes valeurs car il ont le plus d'inertie)

eigval = sorted(eigval, reverse=True)

print(eigval)
print("-----------------------------------------------------------------------------")

# Inertie de chaque composante principale 

eig_inertie = eigval / np.sum(eigval)

print(eig_inertie)
print("-----------------------------------------------------------------------------")

# Inertie cumulée

eig_cum = np.cumsum(eig_inertie)

print(eig_cum)
print("-----------------------------------------------------------------------------")



-----------------------------------------------------------------------------
[[ 0.60302269 -1.06904497 -1.81621654 -1.81621654]
 [ 1.20604538 -1.06904497 -0.47087096 -1.14354375]
 [ 0.90453403 -1.06904497  0.20180184 -1.14354375]
 [-0.90453403  1.60356745  1.54714743  0.20180184]
 [-0.60302269  0.26726124  0.87447463  0.20180184]
 [-1.50755672  0.26726124  0.87447463  0.20180184]
 [-1.20604538  0.26726124 -0.47087096  1.54714743]
 [ 0.30151134 -1.06904497 -0.47087096  0.87447463]
 [ 1.50755672  1.60356745 -1.14354375  0.20180184]
 [-0.30151134  0.26726124  0.87447463  0.87447463]]
-----------------------------------------------------------------------------
[[ 1.         -0.32232919 -0.62873728 -0.56789174]
 [-0.32232919  1.          0.39551461  0.48540429]
 [-0.62873728  0.39551461  1.          0.36651584]
 [-0.56789174  0.48540429  0.36651584  1.        ]]
-----------------------------------------------------------------------------
[2.39089885 0.27438366 0.75031143 0.58440607]
----

## 2-

In [4]:

# Affichage des résultats

mat = np.hstack((np.hstack((np.array(eigval).reshape(-1,1), eig_inertie.reshape(-1,1))), eig_cum.reshape(-1,1)))
print(mat)



[[2.39089885 0.59772471 0.59772471]
 [0.75031143 0.18757786 0.78530257]
 [0.58440607 0.14610152 0.93140409]
 [0.27438366 0.06859591 1.        ]]
