In [91]:
import math
import statistics as st
import numpy as np
import pandas as pd
import scipy 
import matplotlib.pyplot as plt 

In [92]:
X_list=[
    [14, 13, 1.50, 45],
    [16, 13, 1.60, 50],
    [15, 13, 1.65, 50],
    [9 , 15, 1.75, 60],
    [10, 14, 1.70, 60],
    [7 , 14, 1.70, 60],
    [8 , 14, 1.60, 70],
    [13, 13, 1.60, 65],
    [17, 15, 1.55, 60],
    [11, 14, 1.70, 65]
]

In [93]:
ind=list()
for i in range(10):
  ind.append('enfant'+str(i+1))
ind

['enfant1',
 'enfant2',
 'enfant3',
 'enfant4',
 'enfant5',
 'enfant6',
 'enfant7',
 'enfant8',
 'enfant9',
 'enfant10']

In [94]:
X=pd.DataFrame(X_list,columns=['moy','age','taille','poid'],index=ind)
# X=pd.DataFrame(X_list)
X

moy  age  taille  poid
enfant1    14   13    1.50    45
enfant2    16   13    1.60    50
enfant3    15   13    1.65    50
enfant4     9   15    1.75    60
enfant5    10   14    1.70    60
enfant6     7   14    1.70    60
enfant7     8   14    1.60    70
enfant8    13   13    1.60    65
enfant9    17   15    1.55    60
enfant10   11   14    1.70    65

1) Afficher la matrice centrée réduite de la matrice des données.

In [95]:
centreG = [round(X[col].mean(),3) for col in X.columns]
centreG

[12.0, 13.8, 1.635, 58.5]

In [96]:
X_centre = X-centreG
X_centre

moy  age  taille  poid
enfant1   2.0 -0.8  -0.135 -13.5
enfant2   4.0 -0.8  -0.035  -8.5
enfant3   3.0 -0.8   0.015  -8.5
enfant4  -3.0  1.2   0.115   1.5
enfant5  -2.0  0.2   0.065   1.5
enfant6  -5.0  0.2   0.065   1.5
enfant7  -4.0  0.2  -0.035  11.5
enfant8   1.0 -0.8  -0.035   6.5
enfant9   5.0  1.2  -0.085   1.5
enfant10 -1.0  0.2   0.065   6.5

In [97]:
X_eqrt = np.std(X)
X_eqrt

moy       3.316625
age       0.748331
taille    0.074330
poid      7.433034
dtype: float64

In [98]:
X_centre_reduite = X_centre / X_eqrt
X_centre_reduite

moy       age    taille      poid
enfant1   0.603023 -1.069045 -1.816217 -1.816217
enfant2   1.206045 -1.069045 -0.470871 -1.143544
enfant3   0.904534 -1.069045  0.201802 -1.143544
enfant4  -0.904534  1.603567  1.547147  0.201802
enfant5  -0.603023  0.267261  0.874475  0.201802
enfant6  -1.507557  0.267261  0.874475  0.201802
enfant7  -1.206045  0.267261 -0.470871  1.547147
enfant8   0.301511 -1.069045 -0.470871  0.874475
enfant9   1.507557  1.603567 -1.143544  0.201802
enfant10 -0.301511  0.267261  0.874475  0.874475

***2***

Les  valeurs  propres  de  la  matrice  des  corrélations  R  des  données  de  la  matrice  X 
(déjà calculées) sur la première colonne.

In [99]:
X_correlation = X.corr()
X_correlation

moy       age    taille      poid
moy     1.000000 -0.322329 -0.628737 -0.567892
age    -0.322329  1.000000  0.395515  0.485404
taille -0.628737  0.395515  1.000000  0.366516
poid   -0.567892  0.485404  0.366516  1.000000

In [100]:
X_corr_val_propre, X_corr_val_propre_liste= np.linalg.eig(X_correlation)

In [101]:
X_corr_val_propre

array([2.39089885, 0.27438366, 0.75031143, 0.58440607])

In [102]:
X_corr_val_propre_liste

array([[ 0.53834812, -0.67153553, -0.43812579, -0.25935907],
       [-0.44530321,  0.28548823, -0.70578764, -0.47123808],
       [-0.50383507, -0.5041931 ,  0.46470353, -0.52534767],
       [-0.50797301, -0.46187209, -0.30652934,  0.65930066]])

Le Taux d’inertie (par rapport à l’inertie totale) projeté sur chaque axe principal 
sur la 2ème colonne.

In [103]:
#  trie des valeurs propres 

X_corr_val_propre = sorted(X_corr_val_propre, reverse=True)
X_corr_val_propre

[2.3908988468752517,
 0.7503114312990603,
 0.584406066023634,
 0.27438365580205254]

In [104]:
inertie = X_corr_val_propre/ np.sum(X_corr_val_propre)
inertie

array([0.59772471, 0.18757786, 0.14610152, 0.06859591])

Les Taux cumulés de l’information retenue sur la dernière colonne.

In [105]:
inertie_cumule = np.cumsum(inertie)
inertie_cumule

array([0.59772471, 0.78530257, 0.93140409, 1.        ])

In [106]:
mat = np.hstack((np.hstack((np.array(X_corr_val_propre).reshape(-1,1),
                             inertie.reshape(-1,1))), inertie_cumule.reshape(-1,1)))
mat

array([[2.39089885, 0.59772471, 0.59772471],
       [0.75031143, 0.18757786, 0.78530257],
       [0.58440607, 0.14610152, 0.93140409],
       [0.27438366, 0.06859591, 1.        ]])

In [114]:
c0 = np.dot(X_centre_reduite, X_corr_val_propre_liste[0].T)
c1 = np.dot(X_centre_reduite, X_corr_val_propre_liste[1].T)
c2 = np.dot(X_centre_reduite, X_corr_val_propre_liste[2].T)
c3 = np.dot(X_centre_reduite, X_corr_val_propre_liste[3].T)

print(c0,"\n\n" ,c1,"\n\n",c2 ,"\n\n", c3)

[ 2.30932135  1.87006309  1.41302973 -2.29399104 -0.93958058 -1.42653478
 -1.0237137   0.85971752  0.18341469 -0.9517263 ] 

 [ 1.56400589  0.02896063 -0.31153954 -0.3264627  -0.36746222  0.03532969
  0.21661592 -0.51921458  0.49848213 -0.81871523] 

 [ 0.34532402  0.3132998   0.7778052   0.26017706  0.46942802  0.92516399
 -0.55870901 -0.2911255  -2.20549252 -0.03587105] 

 [-0.45326633 -0.72847986 -0.78151418 -0.62236216  0.0478747   0.50735357
  1.65356908  1.06147987 -1.02286337  0.33820869]
